### ISSUE TITLE
Is this dangerous on laptops?

### ISSUE THREAD

**Issue by caniko** [e-tho/ucodenix#2]
Hello, I was wondering if you could provide your opinion on the use of your flake in laptops, considering they have dedicated motherboards, and other hardware.

To my understanding it shouldn't be an issue. I just want to avoid bricking my device.

Just trying to be thorough in my research before delving in. Yes, it is provided as is. I just want an opinion, no strings attached.

Thanks.

**Comment by e-tho** [comment]
Microcodes are obtained from official sources and are tested for their integrity, size, etc. 

The Linux kernel provides safeguards and will not load the microcode if it is not identified as compatible with your CPU, falling back to the one provided by the BIOS.

Most microcode updates provided by AMD are minor optimizations, though sometimes they include patches for vulnerabilities. 

I personally trust the sources, AMD, and the kernel's security measures enough to use this flake without concern, but it is my duty to inform users since we are dealing with hardware, and zero risk does not exist.

**Comment by caniko** [comment]
Well, I have boarded the train 😁
